# 6. Numpy basics

The structures offered by Python are limited, especially if we deal with the multi-dimensional lists that images are. The solution to this is the Numpy package, which offers a new object called an array. On top of offering this structure, Numpy also offers a vast number of functions that operate directly on arrays, sparing us the tedious task of making sure we handle all the pixels of an image. Let's first import Numpy:

In [1]:
import numpy as np
from svg import numpy_to_svg

## 6.1 What is an array

Now let us create arrays. The two simplest ways of doing that is to create arrays filled with 0's or 1's. For example to create a 6x4 array of zeros:

In [2]:
myarray = np.zeros((4,6))

An array is just a matrix, i.e. a grid of numbers with multiple dimensions. For example the array above look like this:

In [3]:
numpy_to_svg(myarray)

And the "inside" of the array looks like this:

In [4]:
myarray

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

We see that we have 6 separate list of 4 0's  grouped into a larger list. This entire structure is an array of 6 rows and 4 columns. In the frame of this course you can also see it as a 6x4 pixel image.

Seeing rows and columns as a system of coordinates, we can access to specific pixels. For example the pixels at row = 3 and columns = 2 is: 

In [5]:
myarray[3,2]

0.0

We can even modify its value:

In [6]:
myarray[3,2] = 13

In [7]:
myarray

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 13.,  0.,  0.,  0.]])

Similarly we can crearte an array filled with 1s:

In [8]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

Finally we can create a one-dimensional array with evenly spaced valeus (similar to range) using:

In [9]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

## 6.2 Simple calculus with arrays

The beautiful thing with arrays, is that you can consider them like an object and forget that they are composed of multiple elements. For example we can just add a value to all all pixels using:

In [10]:
myarray + 32

array([[32., 32., 32., 32., 32., 32.],
       [32., 32., 32., 32., 32., 32.],
       [32., 32., 32., 32., 32., 32.],
       [32., 32., 45., 32., 32., 32.]])

Of course as long as we don't reassign this new state to our variable it remains unchanged:

In [11]:
myarray

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 13.,  0.,  0.,  0.]])

We have to write:

In [12]:
myarray = myarray + 32

In [13]:
myarray

array([[32., 32., 32., 32., 32., 32.],
       [32., 32., 32., 32., 32., 32.],
       [32., 32., 32., 32., 32., 32.],
       [32., 32., 45., 32., 32., 32.]])

Note that if we didn't have those nice Numpy properties, we would have to "manually" go through all pixels to adjust their values: 

In [14]:
for x in range(4):
    for y in range(6):
        myarray[x,y] = myarray[x,y] + 5

In [15]:
myarray

array([[37., 37., 37., 37., 37., 37.],
       [37., 37., 37., 37., 37., 37.],
       [37., 37., 37., 37., 37., 37.],
       [37., 37., 50., 37., 37., 37.]])

Of course we can do much more complex operations on these arrays. For example we can use the cosinus function of Numpy and apply it to the entire array:

In [16]:
np.cos(myarray)

array([[0.76541405, 0.76541405, 0.76541405, 0.76541405, 0.76541405,
        0.76541405],
       [0.76541405, 0.76541405, 0.76541405, 0.76541405, 0.76541405,
        0.76541405],
       [0.76541405, 0.76541405, 0.76541405, 0.76541405, 0.76541405,
        0.76541405],
       [0.76541405, 0.76541405, 0.96496603, 0.76541405, 0.76541405,
        0.76541405]])

## 6.3 Operations combining arrays

In addition to operations that apply to entire arrays, we can do also operations combining multiple arrays. For example we can add two arrays:

In [17]:
myarray1 = 2*np.ones((4,4))
myarray2 = 5*np.ones((4,4))
myarray3 = myarray1 * myarray2
myarray3

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

The one important constraint is of course that the two arrays used in an operation need to have the same size. Otherwise Numpy doesn't know which pairs of pixel to consider.

In [18]:
myarray1 = 2*np.ones((3,3))
myarray2 = 5*np.ones((4,4))
myarray3 = myarray1 * myarray2

ValueError: operands could not be broadcast together with shapes (3,3) (4,4) 

## 6.4 Higher dimensions

Until now we have almost only dealt with 2D arrays that look like a simple grid:

In [19]:
myarray = np.ones((5,10))
numpy_to_svg(myarray)

We are not limited to create 1 or 2 dimensional arrays. We can basically create any-dimension array. For example if we do 3D imaging, we are going to have a series of planes assembled in a "cube". For example if we acquired 5 planes of a 10px by 10px image, we would have something like:

In [20]:
array3D = np.ones((10,10,5))

In [21]:
numpy_to_svg(array3D)

In higher dimensions, the array content output is not very readable. To know what we are dealing with, an **extremely** helpul property associated to arrays is shape:

In [23]:
array3D.shape

(10, 10, 5)

This gives us the size of the array in each dimension.

**Note that shape, which is a parameter of the array, is used almost like a method, however without parenthesis.**

## 6.5 Methods and parameters of arrays

Just like variables and structures, arrays have also associated methods. As we have just seen, they also have associated parameters that one can call without (). 

Sometimes it is unclear whether we deal with a method or parameter. Just try and see what gives an error!

These methods/parameters give a lot of information on the array and are very helpful. For example, one can ask what is the largest element:

In [24]:
myarray.max

<function ndarray.max>

This indicates that we actually deal with a method:

In [25]:
myarray.max()

1.0

We can also e.g. calculate the sum of all elements:

In [26]:
myarray.sum()

50.0

You can actively read the documentation to lear about all methods. The simplest is usually just to do a [Google Search](https://www.google.com/search?ei=5rd2XKqwN8SUsAfj7IuICw&q=sum+of+numpy+array&oq=sum+of+numpy+array&gs_l=psy-ab.3..0i7i30l7j0i203l2j0i5i30.23694.24024..24373...0.0..0.66.193.3......0....1..gws-wiz.......0i71.0RxePnmQfcg) for whatever you are looking for.

## 6.6 Logical operations

Just like variables, arrays can be composed of booleans. Usually they are obtained by using a logical operation on a standard array:

In [27]:
myarray = np.zeros((4,4))
myarray[2,3] = 1
myarray

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [28]:
myarray > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

Exactly as for simple variables, we can assign this boolean array to a new variable directly:

In [29]:
myboolean = myarray > 0

In [30]:
myboolean

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

## 6.7 Array slicing

A vast chapter is array slicing, the fact to only consider a part of an array, as when cropping an image for example. We are however going to treat that part later using actual images, to make the examples more understandable.